package dev.auguste.agni_api.core.adapters.events

enum class EventType {
    NOTIFICATION,
    CREATE_EMBEDDING_SERVICE,
    DELETE_EMBEDDING_SERVICE,
    CREATE_EMBEDDING_EXTERNAL_TRANSACTION,
    CREATE_MANY_EMBEDDING_EXTERNAL_TRANSACTION
}