FROM node:25-alpine3.23 as build

RUN apk add --no-cache libc6-compat

RUN addgroup -S nuxt && adduser -S nuxt -G nuxt
USER nuxt:nuxt

WORKDIR /app

ARG NUXT_PUBLIC_API_BASE
ARG NUXT_PUBLIC_API_AGENT

ENV NODE_ENV=production
ENV NUXT_PUBLIC_API_BASE=$NUXT_PUBLIC_API_BASE
ENV NUXT_PUBLIC_API_AGENT=$NUXT_PUBLIC_API_AGENT

COPY apps/agni-web/package.json apps/agni-web/yarn.lock ./ 
RUN yarn install
COPY apps/agni-web/ .
RUN yarn build

FROM node:25-alpine3.23
RUN apk add --no-cache libc6-compat

WORKDIR /app

RUN addgroup -S nuxt && adduser -S nuxt -G nuxt

COPY --from=build --chown=nuxt:nuxt /app/.output ./

USER nuxt

ENV PORT=8080
ENV HOST=0.0.0.0
EXPOSE 8080
CMD [ "node", "server/index.mjs" ]