FROM node:24-alpine AS base

FROM base AS builder
RUN apk update 
RUN apk add --no-cache libc6-compat 

# Set working directory
WORKDIR /app
RUN corepack enable
RUN yarn global add turbo

COPY . .
RUN turbo prune agni-web --docker
RUN ls -la /app/out && ls -la /app/out/json/apps

# Add lockfile and package.json's of isolated subworkspace
FROM base AS installer
RUN apk update
RUN apk add --no-cache libc6-compat
RUN corepack enable
WORKDIR /app


# First install the dependencies (as they change less often)
COPY --from=builder /app/out/json/apps/agni-web/ .
RUN yarn install

# Build the project
COPY --from=builder /app/out/full/apps/agni-web/ . 
RUN yarn build

# Uncomment and use build args to enable remote caching
# ARG TURBO_TEAM
# ENV TURBO_TEAM=$TURBO_TEAM

# ARG TURBO_TOKEN
# ENV TURBO_TOKEN=$TURBO_TOKEN

FROM base AS runner
RUN apk update
RUN apk add --no-cache libc6-compat curl
# ARG ENV_FILE=.env.production
# COPY ${ENV_FILE} .env
WORKDIR /app
COPY --from=installer /app .
COPY ./apps/agni-web/.env.production /app/.output/server/.env

ENV PORT=80
ENV HOST=0.0.0.0

EXPOSE 80

CMD ["node", "/app/.output/server/index.mjs"]  
# /agni-web/