server.port=8081

agni.startup.enabled=false

logging.level.io.modelcontextprotocol.spec.McpStreamableServerSession=ERROR

spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.type=SYNC

spring.datasource.url=${DB_URL:jdbc:postgresql://192.168.2.61:5432/agni_test}
spring.datasource.username=${DB_USERNAME:test}
spring.datasource.password=${DB_PASSWORD:test}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=never

spring.jpa.hibernate.ddl-auto=none

spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.connection-timeout=30000

ai.agent.api.url=${AI_AGENT_API_LINK:http://localhost:8000}

embedding.collection.invoice=${QDRANT_INVOICE_COLLECTION_NAME:test_invoices}
embedding.collection.external-transaction=${QDRANT_EXTERNAL_TRANSACTION_COLLECTION_NAME:test_external_transactions}

app.i18n.default-locale=${I18N_DEFAULT_LOCALE:fr}
app.i18n.locales=${I18N_LOCALES:fr,en}

spring.ai.mcp.server.streamable-http.mcp-endpoint=/mcp

management.endpoints.web.exposure.include=health
